name: GitHub Actions Pipeline CI

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '24.0'
          elixir-version: '1.13.0'
      - name: get deps
        run: mix deps.get
      - name: lint code
        run: mix credo --strict
